### PR TITLE
Create AwardStatus model

### PR DESCRIPTION
**Pull request by vdavez**
Instead of hard coding the award statuses in the AWARD_STATUS_CHOICE list,
this commit creates an AwardStatus model, with `status` and `actor` fields.

This allows for more flexibility in the future with defining statuses and
should make migrations easier to manage.

### CODE REVIEW

**Comment by vdavez** [comment]
@stvnrlly See above. I didn't include the manual migrations, but hopefully this will make it easier in the future... In the meantime, it causes tests to fail. Any ideas on how I might make it actually _work_?

**Comment by vdavez** [comment]
Also, I'm not sure why, but I couldn't get Django to automatically recognize the fixtures file... so I used the following command to load the data:

`./manage.py loaddata acquisitions/fixtures/award_statuses.json`

**Comment by stvnrlly** [comment]
This seems to work on the back-end, but doesn't yet load in the front-end. I'll check that out, with a particular eye towards whether the stages are ordered properly. I think we should be able to make it work.

**Comment by stvnrlly** [comment]
I think this works. I'm going to add a validator to make sure that the acquisition and the award status are in the same track, and see if we can limit the admin site dropdowns based on the track selected.

Also, we may want to create a few fixtures before merging.

**Pull request merged**
